name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          mkdir docs
          echo "main index new" > docs/index.html
          mkdir docs/report
          echo "report index new" > docs/report/index.html
          echo "report subpage new" > docs/report/report.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          keep_files: true

